language: python
env:
  - REQUIREMENTS=requirements/basic_requirements SERVER=gunicorn
  - REQUIREMENTS=requirements/alt_requirements SERVER=gunicorn
  - REQUIREMENTS=requirements/gevent_only SERVER=gevent
  - REQUIREMENTS=requirements/eventlet_only SERVER=eventlet
  - REQUIREMENTS=requirements/uwsgi_requirements SERVER=uwsgi

jobs:
  include:
    - stage: main_version_testing
      python:
        - "2.7"
        - "3.6"
        - 'pypy'
    - stage: full_version_testing
      if: branch = master
      python:
        - "3.3"
        - "3.4"
        - "nightly"
        - "pypy-5.3.1"
        - "pypy-5.4"
        - "pypy-5.4.1"
  allow_failures:
    - python: nightly
    - python: pypy-5.3.1

install:
  - pip install pip-tools
  - pip-compile ${REQUIREMENTS}.in > ${REQUIREMENTS}.txt
  - pip install -r $REQUIREMENTS.txt
  
script:
  - flake8 .
  - python -m unittest discover
  - python -m tools.server_test
