language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - 'pypy'
  - 'pypy-5.3.1' # Other versions of pypy are available: see https://github.com/travis-ci/travis-ci/issues/4756
  - 'pypy-5.4'
  - 'pypy-5.4.1'
env:
  - REQUIREMENTS=requirements/basic_requirements
  - REQUIREMENTS=requirements/alt_requirements
  - REQUIREMENTS=requirements/gevent_only
  - REQUIREMENTS=requirements/eventlet_only
  - REQUIREMENTS=requirements/uwsgi_requirements

matrix:
  allow_failures:
    - python: nightly
    - python: pypy-5.3.1

install:
  - pip install pip-tools
  - pip-compile ${REQUIREMENTS}.in > ${REQUIREMENTS}.txt
  - pip install -r $REQUIREMENTS.txt
  
script:
  - flake8 .
  - python -m unittest discover
